vim.g.mapleader = ' '
-- vim.keymap.set('n', '<leader>pv', vim.cmd.Vex)
-- vim.keymap.set('n', '<leader>pl', vim.cmd.Lex)
vim.keymap.set('n', '<leader>w', '<cmd>write<cr>')
vim.keymap.set('n', '<leader>q', '<cmd>quit<cr>')
vim.keymap.set({'n', 'x'}, 'gy', '"+y')
vim.keymap.set({'n', 'x'}, 'gp', '"+p')
-- vim.keymap.set({'n'}, '<leader>z', ':undo<cr>')
vim.keymap.set({'n'}, '<leader>y', ':redo<cr>')
vim.keymap.set('n', '<C-a>', ':keepjumps normal! ggVG<cr>')
vim.keymap.set('n', '<leader>1', ':!python3 %<cr>')
vim.keymap.set('n', '<leader>v', ':vsp<cr>')
vim.keymap.set({'n','i','v'}, '<Up>', '<C-y>')
vim.keymap.set({'n','i','v'}, '<Down>', '<C-e>')
-- vim.keymap.set('n', '<space><space>', '<cmd>Lexplore<cr>')
