vim.g.mapleader = ' '
-- vim.keymap.set('n', '<leader>pv', vim.cmd.Vex)
-- vim.keymap.set('n', '<leader>pl', vim.cmd.Lex)
vim.keymap.set('n', '<leader>w', '<cmd>write<cr>')
vim.keymap.set('n', '<leader>q', '<cmd>quit<cr>')
vim.keymap.set({'n', 'x'}, 'gy', '"+y')
vim.keymap.set({'n', 'x'}, 'gp', '"+p')
-- vim.keymap.set({'n'}, '<leader>z', ':undo<cr>')
vim.keymap.set({'n'}, '<leader>y', ':redo<cr>')
vim.keymap.set('n', '<C-a>', ':keepjumps normal! ggVG<cr>')
vim.keymap.set('n', '<leader>1', ':!python3 %<cr>')
vim.keymap.set('n', '<leader>v', ':vsplit<cr>')
vim.keymap.set({'n','v'}, '<Up>', '<C-y>')
vim.keymap.set({'n','v'}, '<Down>', '<C-e>')
-- vim.keymap.set('n', '<space><space>', '<cmd>Lexplore<cr>')
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "switch window left" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "switch window right" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "switch window down" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "switch window up" })
